### ISSUE TITLE
Mobile number other than 98

### ISSUE THREAD

**Issue by over-soul** [Saeed-Pooyanfar/filimo-plus#1]
Hello,

I noticed mobile number has to start with 98 to login. Can this be changed?

Thank you

**Comment by SaeedDev94** [comment]
Hi, please checkout v1.0.9: [`front: login: customize country code`](https://github.com/Saeed-Pooyanfar/filimo-plus/commit/0e04f4312cc6f910d70061a98870dd876aaa9863)
https://github.com/Saeed-Pooyanfar/filimo-plus/releases/tag/v1.0.9

**Comment by over-soul** [comment]
Thank you!

I am getting this error now:

```sh: 1: cross-env: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! filimo-plus@1.0.9 filimo-plus: `cross-env NODE_ENV=production node app.js`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the filimo-plus@1.0.9 filimo-plus script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-08-21T17_08_02_431Z-debug.log

**Comment by SaeedDev94** [comment]
You are welcome!
Maybe reinstalling dependencies can fix this:
```bash
npm cache clean
rm -rf node_modules
npm install
```
(Also if you are using windows run cmd with admin access)

**Comment by over-soul** [comment]
Thank you very much! It is working and the login screen comes up but when I enter my number nothing happens.

**Comment by SaeedDev94** [comment]
This is login process only, you must [create account manually in filimo](https://www.filimo.com/_/signup) and make sure your [filimo profile](https://www.filimo.com/myaccount) has a valid mobile number
(I guess your mobile number not registered in filimo db)

**Comment by over-soul** [comment]
Yes, I have an account with a valid registered number.

**Comment by SaeedDev94** [comment]
Login with mobile number is working just fine for me, maybe i have to implement login with username/password for you later ...

**Comment by over-soul** [comment]
It is not giving me an error message. I enter the phone number, click on login, screen flashes and goes back to the login screen. I can login with my phone number on filimo.com

**Comment by SaeedDev94** [comment]
With OTP or Password? BTW you can email me your telegram username for further discussion in private
Edit: try v1.1.1:
https://github.com/Saeed-Pooyanfar/filimo-plus/releases/tag/v1.1.2

**Comment by over-soul** [comment]
Fixed. Had to update Nodejs to v 12.x.
