### ISSUE TITLE
مشکل لاگین نشدن

### ISSUE THREAD

**Issue by tntkgb** [Saeed-Pooyanfar/filimo-plus#8]
سلام دوست عزیز
من هرکار میکنم لاگین نمیشه 
اروری که میده 
html.matchAll(...) is not a function or its return value is not iterable
اگه امکانش هست نحوه تنظیم دستی کوکی رو توضیح بدی هم عالی میشه تا نیازی به لاگین نباشه
ممنون

**Comment by SaeedDev94** [comment]
Hi
First: please download filimo-plus from master branch as it contains some important changes you should have.
Second: recently filimo implemented recaptcha for login with OTP. I don't have idea how can i bypass it, but i encourage anyone to contribute if they have any solution for this.
For now you can login with official filimo site and grab `AuthV1` cookie value, then put it into filimo-plus localStorage with `jwt_token` name.

**Comment by 2ndemosthenes** [comment]
@Saeed-Pooyanfar I've tried adding the AuthV1 to Local Storage with browser's developer tools but after refreshing the page it gets renamed to `b_jwt_token` and it shows the login page again.

**Comment by SaeedDev94** [comment]
@2ndemosthenes It's hard to maintain `filimo-plus` for me without almost no support !
However i want to develop a cli version of filimo-plus: `filimo-plus-cli`
So you can wait for that ;)
EOL `filimo-plus`
R.I.P.

**Comment by SaeedDev94** [comment]
@2ndemosthenes take a look at https://github.com/Saeed-Pooyanfar/filimo-plus-cli
